var l=void 0,m=!0,p=null,u=!1,v,w=this;
function y(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function A(a){return"string"==typeof a}function aa(a){var b=typeof a;return"object"==b&&a!=p||"function"==b}var B="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ba=0;function C(a,b){var c=a.split("."),d=w;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==l?d[f]=b:d=d[f]?d[f]:d[f]={}};function ca(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function da(a){if(!ea.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(fa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ga,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ha,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ia,"&quot;"));return a}var fa=/&/g,ga=/</g,ha=/>/g,ia=/\"/g,ea=/[&<>\"]/;var D,ja,ka,la;function ma(){return w.navigator?w.navigator.userAgent:p}la=ka=ja=D=u;var na;if(na=ma()){var oa=w.navigator;D=0==na.indexOf("Opera");ja=!D&&-1!=na.indexOf("MSIE");ka=!D&&-1!=na.indexOf("WebKit");la=!D&&!ka&&"Gecko"==oa.product}var pa=D,E=ja,F=la,G=ka,qa=w.navigator,ra=-1!=(qa&&qa.platform||"").indexOf("Mac");function sa(){var a=w.document;return a?a.documentMode:l}var ta;
a:{var ua="",H;if(pa&&w.opera)var va=w.opera.version,ua="function"==typeof va?va():va;else if(F?H=/rv\:([^\);]+)(\)|;)/:E?H=/MSIE\s+([^\);]+)(\)|;)/:G&&(H=/WebKit\/(\S+)/),H)var wa=H.exec(ma()),ua=wa?wa[1]:"";if(E){var xa=sa();if(xa>parseFloat(ua)){ta=String(xa);break a}}ta=ua}var ya={};
function I(a){var b;if(!(b=ya[a])){b=0;for(var c=ca(String(ta)).split("."),d=ca(String(a)).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",h=d[e]||"",j=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var q=j.exec(g)||["","",""],r=k.exec(h)||["","",""];if(0==q[0].length&&0==r[0].length)break;b=((0==q[1].length?0:parseInt(q[1],10))<(0==r[1].length?0:parseInt(r[1],10))?-1:(0==q[1].length?0:parseInt(q[1],10))>(0==r[1].length?0:parseInt(r[1],10))?1:0)||((0==q[2].length)<
(0==r[2].length)?-1:(0==q[2].length)>(0==r[2].length)?1:0)||(q[2]<r[2]?-1:q[2]>r[2]?1:0)}while(0==b)}b=ya[a]=0<=b}return b}var za=w.document,Aa=!za||!E?l:sa()||("CSS1Compat"==za.compatMode?parseInt(ta,10):5);function J(a,b){this.type=a;this.currentTarget=this.target=b}J.prototype.w=u;J.prototype.defaultPrevented=u;J.prototype.L=m;J.prototype.preventDefault=function(){this.defaultPrevented=m;this.L=u};function Ba(){}var Ca=0;v=Ba.prototype;v.key=0;v.h=u;v.m=u;v.n=function(a,b,c,d,f,e){if("function"==y(a))this.C=m;else if(a&&a.handleEvent&&"function"==y(a.handleEvent))this.C=u;else throw Error("Invalid listener argument");this.o=a;this.G=b;this.src=c;this.type=d;this.capture=!!f;this.A=e;this.m=u;this.key=++Ca;this.h=u};v.handleEvent=function(a){return this.C?this.o.call(this.A||this.src,a):this.o.handleEvent.call(this.o,a)};var Da="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ea(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Da.length;e++)c=Da[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Fa=!E||E&&9<=Aa,Ga=E&&!I("9");!G||I("528");F&&I("1.9b")||E&&I("8")||pa&&I("9.5")||G&&I("528");F&&!I("8")||E&&I("9");var K=Array.prototype,Ha=K.indexOf?function(a,b,c){return K.indexOf.call(a,b,c)}:function(a,b,c){c=c==p?0:0>c?Math.max(0,a.length+c):c;if(A(a))return!A(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ia=K.forEach?function(a,b,c){K.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=A(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function Ja(a,b,c){return 2>=arguments.length?K.slice.call(a,b):K.slice.call(a,b,c)};function Ka(a){Ka[" "](a);return a}Ka[" "]=function(){};function L(a,b){a&&this.n(a,b)}function La(){}La.prototype=J.prototype;L.M=J.prototype;L.prototype=new La;v=L.prototype;v.constructor=L;v.target=p;v.relatedTarget=p;v.offsetX=0;v.offsetY=0;v.clientX=0;v.clientY=0;v.screenX=0;v.screenY=0;v.button=0;v.keyCode=0;v.charCode=0;v.ctrlKey=u;v.altKey=u;v.shiftKey=u;v.metaKey=u;v.K=u;v.z=p;
v.n=function(a,b){var c=this.type=a.type;J.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(F){var f;a:{try{Ka(d.nodeName);f=m;break a}catch(e){}f=u}f||(d=p)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=G||a.offsetX!==l?a.offsetX:a.layerX;this.offsetY=G||a.offsetY!==l?a.offsetY:a.layerY;this.clientX=a.clientX!==l?a.clientX:a.pageX;this.clientY=a.clientY!==l?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.K=ra?a.metaKey:a.ctrlKey;this.state=a.state;this.z=a;a.defaultPrevented&&this.preventDefault();delete this.w};
v.preventDefault=function(){L.M.preventDefault.call(this);var a=this.z;if(a.preventDefault)a.preventDefault();else if(a.returnValue=u,Ga)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var M={},N={},O={},P={};
function Ma(a,b,c,d,f){if("array"==y(b))for(var e=0;e<b.length;e++)Ma(a,b[e],c,d,f);else a:{if(!b)throw Error("Invalid event type");d=!!d;var g=N;b in g||(g[b]={c:0,e:0});g=g[b];d in g||(g[d]={c:0,e:0},g.c++);var g=g[d],e=a[B]||(a[B]=++ba),h;g.e++;if(g[e]){h=g[e];for(var j=0;j<h.length;j++)if(g=h[j],g.o==c&&g.A==f){if(g.h)break;h[j].m=u;break a}}else h=g[e]=[],g.c++;var k=Na,q=Fa?function(a){return k.call(q.src,q.key,a)}:function(a){a=k.call(q.src,q.key,a);if(!a)return a},j=q;j.src=a;g=new Ba;g.n(c,
j,a,b,d,f);g.m=u;c=g.key;j.key=c;h.push(g);M[c]=g;O[e]||(O[e]=[]);O[e].push(g);a.addEventListener?(a==w||!a.I)&&a.addEventListener(b,j,d):a.attachEvent(b in P?P[b]:P[b]="on"+b,j)}}function Oa(a,b,c,d){if(!d.p&&d.F){for(var f=0,e=0;f<d.length;f++)d[f].h?d[f].G.src=p:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.F=u;0==e&&(delete N[a][b][c],N[a][b].c--,0==N[a][b].c&&(delete N[a][b],N[a].c--),0==N[a].c&&delete N[a])}}
function Pa(a,b,c,d,f){var e=1;b=b[B]||(b[B]=++ba);if(a[b]){a.e--;a=a[b];a.p?a.p++:a.p=1;try{for(var g=a.length,h=0;h<g;h++){var j=a[h];j&&!j.h&&(e&=Qa(j,f)!==u)}}finally{a.p--,Oa(c,d,b,a)}}return Boolean(e)}
function Qa(a,b){if(a.m){var c=a.key;if(M[c]){var d=M[c];if(!d.h){var f=d.src,e=d.type,g=d.G,h=d.capture;f.removeEventListener?(f==w||!f.I)&&f.removeEventListener(e,g,h):f.detachEvent&&f.detachEvent(e in P?P[e]:P[e]="on"+e,g);f=f[B]||(f[B]=++ba);if(O[f]){var g=O[f],j=Ha(g,d);0<=j&&K.splice.call(g,j,1);0==g.length&&delete O[f]}d.h=m;if(d=N[e][h][f])d.F=m,Oa(e,h,f,d);delete M[c]}}}return a.handleEvent(b)}
function Na(a,b){if(!M[a])return m;var c=M[a],d=c.type,f=N;if(!(d in f))return m;var f=f[d],e,g;if(!Fa){var h;if(!(h=b))a:{h=["window","event"];for(var j=w;e=h.shift();)if(j[e]!=p)j=j[e];else{h=p;break a}h=j}e=h;h=m in f;j=u in f;if(h){if(0>e.keyCode||e.returnValue!=l)return m;a:{var k=u;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(q){k=m}if(k||e.returnValue==l)e.returnValue=m}}k=new L;k.n(e,this);e=m;try{if(h){for(var r=[],s=k.currentTarget;s;s=s.parentNode)r.push(s);g=f[m];g.e=g.c;for(var x=r.length-
1;!k.w&&0<=x&&g.e;x--)k.currentTarget=r[x],e&=Pa(g,r[x],d,m,k);if(j){g=f[u];g.e=g.c;for(x=0;!k.w&&x<r.length&&g.e;x++)k.currentTarget=r[x],e&=Pa(g,r[x],d,u,k)}}else e=Qa(c,k)}finally{r&&(r.length=0)}return e}d=new L(b,this);return e=Qa(c,d)};var Q;Q=function(){return m};var Ra;function Sa(a,b){var c;c=a.className;c=A(c)&&c.match(/\S+/g)||[];for(var d=Ja(arguments,1),f=c.length+d.length,e=c,g=0;g<d.length;g++)0<=Ha(e,d[g])||e.push(d[g]);a.className=c.join(" ");return c.length==f};var Ta=!E||E&&9<=Aa;!F&&!E||E&&E&&9<=Aa||F&&I("1.9.1");E&&I("9");var Ua={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Va(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!Ta&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',da(g.name),'"');if(g.type){e.push(' type="',da(g.type),'"');var h={};Ea(h,g);delete h.type;g=h}e.push(">");e=e.join("")}e=f.createElement(e);if(g)if(A(g))e.className=g;else if("array"==y(g))Sa.apply(p,[e].concat(g));else{var j=e,h=function(a,b){"style"==b?j.style.cssText=a:"class"==b?j.className=a:"for"==b?j.htmlFor=a:b in Ua?j.setAttribute(Ua[b],a):0==b.lastIndexOf("aria-",
0)||0==b.lastIndexOf("data-",0)?j.setAttribute(b,a):j[b]=a},k;for(k in g)h.call(l,g[k],k)}if(2<d.length){var q=f,r=e,f=function(a){a&&r.appendChild(A(a)?q.createTextNode(a):a)};for(k=2;k<d.length;k++)if(h=d[k],g=y(h),("array"==g||"object"==g&&"number"==typeof h.length)&&!(aa(h)&&0<h.nodeType)){var s;a:{if(h&&"number"==typeof h.length){if(aa(h)){s="function"==typeof h.item||"string"==typeof h.item;break a}if("function"==y(h)){s="function"==typeof h.item;break a}}s=u}g=Ia;if(s)if(s=h.length,0<s){for(var x=
Array(s),t=0;t<s;t++)x[t]=h[t];h=x}else h=[];g(h,f)}else f(h)}return e}function R(a){this.t=a||w.document||document}R.prototype.createElement=function(a){return this.t.createElement(a)};R.prototype.createTextNode=function(a){return this.t.createTextNode(a)};R.prototype.appendChild=function(a,b){a.appendChild(b)};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
function S(a,b){var c=b||[];a&&c.push(a);return c}var Wa=G&&"BackCompat"==document.compatMode,Xa=document.firstChild.children?"children":"childNodes",T=u;
function Ya(a){function b(){0<=k&&(n.id=c(k,t).replace(/\\/g,""),k=-1);if(0<=q){var a=q==t?p:c(q,t);0>">~+".indexOf(a)?n.a=a:n.r=a;q=-1}0<=j&&(n.b.push(c(j+1,t).replace(/\\/g,"")),j=-1)}function c(b,c){return ca(a.slice(b,c))}a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=[],f=-1,e=-1,g=-1,h=-1,j=-1,k=-1,q=-1,r="",s="",x,t=0,pb=a.length,n=p,z=p;r=s,s=a.charAt(t),t<pb;t++)if("\\"!=r)if(n||(x=t,n={g:p,d:[],l:[],b:[],a:p,r:p,id:p,u:function(){return T?this.J:this.a}},q=t),0<=f)if("]"==s){z.s?
z.v=c(g||f+1,t):z.s=c(f+1,t);if((f=z.v)&&('"'==f.charAt(0)||"'"==f.charAt(0)))z.v=f.slice(1,-1);n.l.push(z);z=p;f=g=-1}else"="==s&&(g=0<="|~^$*".indexOf(r)?r:"",z.type=g+s,z.s=c(f+1,t-g.length),g=t+1);else 0<=e?")"==s&&(0<=h&&(z.value=c(e+1,t)),h=e=-1):"#"==s?(b(),k=t+1):"."==s?(b(),j=t):":"==s?(b(),h=t):"["==s?(b(),f=t,z={}):"("==s?(0<=h&&(z={name:c(h+1,t),value:p},n.d.push(z)),e=t):" "==s&&r!=s&&(b(),0<=h&&n.d.push({name:c(h+1,t)}),n.D=n.d.length||n.l.length||n.b.length,n.N=n.g=c(x,t),n.J=n.a=n.r?
p:n.a||"*",n.a&&(n.a=n.a.toUpperCase()),d.length&&d[d.length-1].r&&(n.B=d.pop(),n.g=n.B.g+" "+n.g),d.push(n),n=p);return d}function U(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function Za(a){return 1==a.nodeType}function V(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(T?a.getAttribute(b):a.getAttribute(b,2))||""}
var $a={"*=":function(a,b){return function(c){return 0<=V(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==V(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+V(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+V(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+V(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return V(c,a)==b}}},ab="undefined"==
typeof document.firstChild.nextElementSibling,W=!ab?"nextElementSibling":"nextSibling",bb=!ab?"previousElementSibling":"previousSibling",cb=ab?Za:Q;function db(a){for(;a=a[bb];)if(cb(a))return u;return m}function eb(a){for(;a=a[W];)if(cb(a))return u;return m}function fb(a){var b=a.parentNode,c=0,d=b[Xa],f=a._i||-1,e=b._l||-1;if(!d)return-1;d=d.length;if(e==d&&0<=f&&0<=e)return f;b._l=d;f=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[W])cb(b)&&(b._i=++c,a===b&&(f=c));return f}
function gb(a){return!(fb(a)%2)}function hb(a){return fb(a)%2}
var ib={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return db},"last-child":function(){return eb},"only-child":function(){return function(a){return!db(a)||!eb(a)?u:m}},empty:function(){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return u}return m}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=Ya(b)[0],d={f:1};"*"!=c.a&&(d.a=1);c.b.length||(d.b=1);var f=X(c,d);return function(a){return!f(a)}},"nth-child":function(a,b){if("odd"==b)return hb;if("even"==b)return gb;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,f=c[1]?parseInt(c[1],10):0,e=0,g=-1;0<d?0>f?f=f%d&&d+f%d:0<f&&(f>=d&&(e=f-f%d),f%=d):0>d&&(d*=-1,0<f&&(g=f,f%=d));if(0<d)return function(a){a=fb(a);return a>=e&&(0>g||a<=g)&&a%d==f};b=f}var h=parseInt(b,10);return function(a){return fb(a)==
h}}},jb=E?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return T?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function X(a,b){if(!a)return Q;b=b||{};var c=p;b.f||(c=U(c,Za));b.a||"*"!=a.a&&(c=U(c,function(b){return b&&b.tagName==a.u()}));b.b||Ia(a.b,function(a,b){var e=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=U(c,function(a){return e.test(a.className)});c.count=b});b.d||Ia(a.d,function(a){var b=a.name;ib[b]&&(c=U(c,ib[b](b,a.value)))});b.l||Ia(a.l,function(a){var b,e=a.s;a.type&&$a[a.type]?b=$a[a.type](e,a.v):e.length&&(b=jb(e));b&&(c=U(c,b))});b.id||a.id&&(c=U(c,function(b){return!!b&&b.id==a.id}));c||"default"in
b||(c=Q);return c}var kb={};
function lb(a){var b=kb[a.g];if(b)return b;var c=a.B,c=c?c.r:"",d=X(a,{f:1}),f="*"==a.a,e=document.getElementsByClassName;if(c)if(e={f:1},f&&(e.a=1),d=X(a,e),"+"==c)var g=d,b=function(a,b,c){for(;a=a[W];)if(!ab||Za(a)){(!c||mb(a,c))&&g(a)&&b.push(a);break}return b};else if("~"==c)var h=d,b=function(a,b,c){for(a=a[W];a;){if(cb(a)){if(c&&!mb(a,c))break;h(a)&&b.push(a)}a=a[W]}return b};else{if(">"==c)var j=d,j=j||Q,b=function(a,b,c){for(var d=0,f=a[Xa];a=f[d++];)cb(a)&&((!c||mb(a,c))&&j(a,d))&&b.push(a);
return b}}else if(a.id)d=!a.D&&f?Q:X(a,{f:1,id:1}),b=function(b,c){var f;f=b?new R(9==b.nodeType?b:b.ownerDocument||b.document):Ra||(Ra=new R);var e=a.id;if(e=(f=A(e)?f.t.getElementById(e):e)&&d(f))if(!(e=9==b.nodeType)){for(e=f.parentNode;e&&e!=b;)e=e.parentNode;e=!!e}if(e)return S(f,c)};else if(e&&/\{\s*\[native code\]\s*\}/.test(String(e))&&a.b.length&&!Wa)var d=X(a,{f:1,b:1,id:1}),k=a.b.join(" "),b=function(a,b){for(var c=S(0,b),f,e=0,g=a.getElementsByClassName(k);f=g[e++];)d(f,a)&&c.push(f);
return c};else!f&&!a.D?b=function(b,c){for(var d=S(0,c),f,e=0,g=b.getElementsByTagName(a.u());f=g[e++];)d.push(f);return d}:(d=X(a,{f:1,a:1,id:1}),b=function(b,c){for(var f=S(0,c),e,g=0,h=b.getElementsByTagName(a.u());e=h[g++];)d(e,b)&&f.push(e);return f});return kb[a.g]=b}var nb={},ob={};
function qb(a){var b=Ya(ca(a));if(1==b.length){var c=lb(b[0]);return function(a){if(a=c(a,[]))a.q=m;return a}}return function(a){a=S(a);for(var c,e,g=b.length,h,j,k=0;k<g;k++){j=[];c=b[k];e=a.length-1;0<e&&(h={},j.q=m);e=lb(c);for(var q=0;c=a[q];q++)e(c,j,h);if(!j.length)break;a=j}return j}}var rb=!!document.querySelectorAll&&(!G||I("526"));
function sb(a,b){if(rb){var c=ob[a];if(c&&!b)return c}if(c=nb[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=m);if(rb&&!b&&-1==">~+".indexOf(c)&&(!E||-1==a.indexOf(":"))&&!(Wa&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var f=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return ob[a]=function(b){try{if(!(9==b.nodeType||d))throw"";var c=b.querySelectorAll(f);E?c.H=m:c.q=m;return c}catch(e){return sb(a,m)(b)}}}var e=a.split(/\s*,\s*/);return nb[a]=
2>e.length?qb(a):function(a){for(var b=0,c=[],d;d=e[b++];)c=c.concat(qb(d)(a));return c}}var Y=0,tb=E?function(a){return T?a.getAttribute("_uid")||a.setAttribute("_uid",++Y)||Y:a.uniqueID}:function(a){return a._uid||(a._uid=++Y)};function mb(a,b){if(!b)return 1;var c=tb(a);return!b[c]?b[c]=1:0}
function ub(a){if(a&&a.q)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;Y++;if(E&&T){var c=Y+"";a[0].setAttribute("_zipIdx",c);for(var d=1,f;f=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(f),f.setAttribute("_zipIdx",c)}else if(E&&a.H)try{for(d=1;f=a[d];d++)Za(f)&&b.push(f)}catch(e){}else{a[0]&&(a[0]._zipIdx=Y);for(d=1;f=a[d];d++)a[d]._zipIdx!=Y&&b.push(f),f._zipIdx=Y}return b}
function vb(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!A(a))return[a];if(A(b)&&(b=A(b)?document.getElementById(b):b,!b))return[];b=b||document;var c=b.ownerDocument||b.documentElement;T=b.contentType&&"application/xml"==b.contentType||pa&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(E?c.xml:b.xmlVersion||c.xmlVersion);return(c=sb(a)(b))&&c.q?c:ub(c)}vb.d=ib;C("goog.dom.query",vb);C("goog.dom.query.pseudos",vb.d);function Z(a,b,c){this.i=a;this.j=b;this.k=c}C("concerto.player.Settings",Z);Z.screen_id=Z.i;Z.server_url=Z.j;Z.server_version=Z.k;Z.prototype.save=function(){localStorage.screen_id=this.i;localStorage.server_url=this.j;localStorage.server_version=this.k};C("concerto.player.Settings.save",Z.prototype.save);Z.prototype.load=function(){this.i=localStorage.screen_id;this.j=localStorage.server_url;this.k=localStorage.server_version};C("concerto.player.Settings.load",Z.prototype.load);
Z.prototype.url=function(){return 1==this.k?this.j+"/screen/?mac="+this.i:2==this.k?this.j+"/frontend/"+this.i:p};C("concerto.player.Settings.url",Z.prototype.url);C("concerto.player.Settings",Z);function wb(a){67==a.keyCode?window.location="settings.html":65!=a.keyCode&&76==a.keyCode&&(a=new Z,a.load(),window.location=a.url())}function xb(){if(navigator.onLine){var a=new Z;a.load();window.location=a.url()}else window.location.reload(m)}C("concerto.player.Settings.load",Z.load);
Ma(window,"load",function(){var a=Va("div",{id:"status-message"},"Initializing...");(A("container")?document.getElementById("container"):"container").appendChild(a);Ma(document,"keyup",wb);var b=new Z;b.load();if(b.url()==p)window.location="settings.html";else if(navigator.onLine)setInterval(xb,5E3);else{if("textContent"in a)a.textContent="No internet connectivity.";else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data="No internet connectivity."}else{for(;b=
a.firstChild;)a.removeChild(b);a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode("No internet connectivity."))}setInterval(function(){window.location.reload(m)},1E4)}});
