var h=void 0,j=!0,k=null,n=!1,v,aa=aa||{},w=this;function ba(a){a=a.split(".");for(var b=w,c;c=a.shift();)if(b[c]!=k)b=b[c];else return k;return b}function ca(){}
function x(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function da(a){var b=x(a);return"array"==b||"object"==b&&"number"==typeof a.length}function y(a){return"string"==typeof a}function ea(a){var b=typeof a;return"object"==b&&a!=k||"function"==b}function z(a){return a[fa]||(a[fa]=++ga)}var fa="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ga=0;function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ja(a,b,c){ja=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return ja.apply(k,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function C(a,b){var c=a.split("."),d=w;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==h?d[f]=b:d=d[f]?d[f]:d[f]={}}
function D(a,b){function c(){}c.prototype=b.prototype;a.aa=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ma(a,b){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,d)}return a}function na(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function oa(a){if(!pa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(qa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ra,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(sa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ta,"&quot;"));return a}var qa=/&/g,ra=/</g,sa=/>/g,ta=/\"/g,pa=/[&<>\"]/;var E,ua,va,wa;function xa(){return w.navigator?w.navigator.userAgent:k}wa=va=ua=E=n;var ya;if(ya=xa()){var za=w.navigator;E=0==ya.indexOf("Opera");ua=!E&&-1!=ya.indexOf("MSIE");va=!E&&-1!=ya.indexOf("WebKit");wa=!E&&!va&&"Gecko"==za.product}var Aa=E,F=ua,G=wa,H=va,Ba=w.navigator,Ca=-1!=(Ba&&Ba.platform||"").indexOf("Mac");function Da(){var a=w.document;return a?a.documentMode:h}var Ea;
a:{var Fa="",Ga;if(Aa&&w.opera)var Ha=w.opera.version,Fa="function"==typeof Ha?Ha():Ha;else if(G?Ga=/rv\:([^\);]+)(\)|;)/:F?Ga=/MSIE\s+([^\);]+)(\)|;)/:H&&(Ga=/WebKit\/(\S+)/),Ga)var Ia=Ga.exec(xa()),Fa=Ia?Ia[1]:"";if(F){var Ja=Da();if(Ja>parseFloat(Fa)){Ea=String(Ja);break a}}Ea=Fa}var Ka={};
function I(a){var b;if(!(b=Ka[a])){b=0;for(var c=na(String(Ea)).split("."),d=na(String(a)).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",l=d[e]||"",m=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var r=m.exec(g)||["","",""],p=q.exec(l)||["","",""];if(0==r[0].length&&0==p[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==p[1].length?0:parseInt(p[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==p[1].length?0:parseInt(p[1],10))?1:0)||((0==r[2].length)<
(0==p[2].length)?-1:(0==r[2].length)>(0==p[2].length)?1:0)||(r[2]<p[2]?-1:r[2]>p[2]?1:0)}while(0==b)}b=Ka[a]=0<=b}return b}var La=w.document,Ma=!La||!F?h:Da()||("CSS1Compat"==La.compatMode?parseInt(Ea,10):5);function J(){0!=Na&&(this.Fa=Error().stack,Oa[z(this)]=this)}var Na=0,Oa={};J.prototype.ca=n;J.prototype.F=function(){if(!this.ca&&(this.ca=j,this.i(),0!=Na)){var a=z(this);delete Oa[a]}};J.prototype.i=function(){this.ua&&Pa.apply(k,this.ua);if(this.oa)for(;this.oa.length;)this.oa.shift()()};function Pa(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];da(d)?Pa.apply(k,d):d&&"function"==typeof d.F&&d.F()}};function K(a,b){this.type=a;this.currentTarget=this.target=b}v=K.prototype;v.i=function(){};v.F=function(){};v.n=n;v.defaultPrevented=n;v.O=j;v.preventDefault=function(){this.defaultPrevented=j;this.O=n};function Qa(){}var Ra=0;v=Qa.prototype;v.key=0;v.p=n;v.D=n;v.I=function(a,b,c,d,f,e){if("function"==x(a))this.ka=j;else if(a&&a.handleEvent&&"function"==x(a.handleEvent))this.ka=n;else throw Error("Invalid listener argument");this.u=a;this.qa=b;this.src=c;this.type=d;this.capture=!!f;this.X=e;this.D=n;this.key=++Ra;this.p=n};v.handleEvent=function(a){return this.ka?this.u.call(this.X||this.src,a):this.u.handleEvent.call(this.u,a)};function Sa(a,b){for(var c in a)b.call(h,a[c],c,a)}function Ta(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ua(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Wa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Va.length;e++)c=Va[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Xa=!F||F&&9<=Ma,Ya=F&&!I("9");!H||I("528");G&&I("1.9b")||F&&I("8")||Aa&&I("9.5")||H&&I("528");G&&!I("8")||F&&I("9");function Za(a){Error.captureStackTrace?Error.captureStackTrace(this,Za):this.stack=Error().stack||"";a&&(this.message=String(a))}D(Za,Error);Za.prototype.name="CustomError";function $a(a,b){b.unshift(a);Za.call(this,ma.apply(k,b));b.shift();this.Ia=a}D($a,Za);$a.prototype.name="AssertionError";function ab(a,b){throw new $a("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var L=Array.prototype,bb=L.indexOf?function(a,b,c){return L.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a.length+c):c;if(y(a))return!y(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},cb=L.forEach?function(a,b,c){L.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=y(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},db=L.filter?function(a,b,c){return L.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,g=y(a)?
a.split(""):a,l=0;l<d;l++)if(l in g){var m=g[l];b.call(c,m,l,a)&&(f[e++]=m)}return f};function eb(a,b){var c=bb(a,b);0<=c&&L.splice.call(a,c,1)}function fb(a,b,c){return 2>=arguments.length?L.slice.call(a,b):L.slice.call(a,b,c)};function gb(a){gb[" "](a);return a}gb[" "]=ca;function hb(a,b){a&&this.I(a,b)}D(hb,K);v=hb.prototype;v.target=k;v.relatedTarget=k;v.offsetX=0;v.offsetY=0;v.clientX=0;v.clientY=0;v.screenX=0;v.screenY=0;v.button=0;v.keyCode=0;v.charCode=0;v.ctrlKey=n;v.altKey=n;v.shiftKey=n;v.metaKey=n;v.Aa=n;v.da=k;
v.I=function(a,b){var c=this.type=a.type;K.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(G){var f;a:{try{gb(d.nodeName);f=j;break a}catch(e){}f=n}f||(d=k)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=H||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=H||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Aa=Ca?a.metaKey:a.ctrlKey;this.state=a.state;this.da=a;a.defaultPrevented&&this.preventDefault();delete this.n};
v.preventDefault=function(){hb.aa.preventDefault.call(this);var a=this.da;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,Ya)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};v.i=function(){};var M={},N={},O={},P={};
function Q(a,b,c,d,f){if("array"==x(b))for(var e=0;e<b.length;e++)Q(a,b[e],c,d,f);else a:{if(!b)throw Error("Invalid event type");d=!!d;var g=N;b in g||(g[b]={b:0,f:0});g=g[b];d in g||(g[d]={b:0,f:0},g.b++);var g=g[d],e=z(a),l;g.f++;if(g[e]){l=g[e];for(var m=0;m<l.length;m++)if(g=l[m],g.u==c&&g.X==f){if(g.p)break;l[m].D=n;break a}}else l=g[e]=[],g.b++;var q=ib,r=Xa?function(a){return q.call(r.src,r.key,a)}:function(a){a=q.call(r.src,r.key,a);if(!a)return a},m=r;m.src=a;g=new Qa;g.I(c,m,a,b,d,f);g.D=
n;c=g.key;m.key=c;l.push(g);M[c]=g;O[e]||(O[e]=[]);O[e].push(g);a.addEventListener?(a==w||!a.ba)&&a.addEventListener(b,m,d):a.attachEvent(b in P?P[b]:P[b]="on"+b,m)}}function jb(a,b,c,d,f){if("array"==x(b))for(var e=0;e<b.length;e++)jb(a,b[e],c,d,f);else{d=!!d;a:{e=N;if(b in e&&(e=e[b],d in e&&(e=e[d],a=z(a),e[a]))){a=e[a];break a}a=k}if(a)for(e=0;e<a.length;e++)if(a[e].u==c&&a[e].capture==d&&a[e].X==f){kb(a[e].key);break}}}
function kb(a){if(M[a]){var b=M[a];if(!b.p){var c=b.src,d=b.type,f=b.qa,e=b.capture;c.removeEventListener?(c==w||!c.ba)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in P?P[d]:P[d]="on"+d,f);c=z(c);O[c]&&(f=O[c],eb(f,b),0==f.length&&delete O[c]);b.p=j;if(b=N[d][e][c])b.na=j,lb(d,e,c,b);delete M[a]}}}
function lb(a,b,c,d){if(!d.K&&d.na){for(var f=0,e=0;f<d.length;f++)d[f].p?d[f].qa.src=k:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.na=n;0==e&&(delete N[a][b][c],N[a][b].b--,0==N[a][b].b&&(delete N[a][b],N[a].b--),0==N[a].b&&delete N[a])}}function mb(a,b,c,d,f){var e=1;b=z(b);if(a[b]){a.f--;a=a[b];a.K?a.K++:a.K=1;try{for(var g=a.length,l=0;l<g;l++){var m=a[l];m&&!m.p&&(e&=nb(m,f)!==n)}}finally{a.K--,lb(c,d,b,a)}}return Boolean(e)}function nb(a,b){a.D&&kb(a.key);return a.handleEvent(b)}
function ib(a,b){if(!M[a])return j;var c=M[a],d=c.type,f=N;if(!(d in f))return j;var f=f[d],e,g;if(!Xa){e=b||ba("window.event");var l=j in f,m=n in f;if(l){if(0>e.keyCode||e.returnValue!=h)return j;a:{var q=n;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(r){q=j}if(q||e.returnValue==h)e.returnValue=j}}q=new hb;q.I(e,this);e=j;try{if(l){for(var p=[],s=q.currentTarget;s;s=s.parentNode)p.push(s);g=f[j];g.f=g.b;for(var A=p.length-1;!q.n&&0<=A&&g.f;A--)q.currentTarget=p[A],e&=mb(g,p[A],d,j,q);if(m){g=
f[n];g.f=g.b;for(A=0;!q.n&&A<p.length&&g.f;A++)q.currentTarget=p[A],e&=mb(g,p[A],d,n,q)}}else e=nb(c,q)}finally{p&&(p.length=0)}return e}d=new hb(b,this);return e=nb(c,d)};var ob=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function pb(){J.call(this)}D(pb,J);v=pb.prototype;v.ba=j;v.$=k;v.addEventListener=function(a,b,c,d){Q(this,a,b,c,d)};v.removeEventListener=function(a,b,c,d){jb(this,a,b,c,d)};
v.dispatchEvent=function(a){var b=a.type||a,c=N;if(b in c){if(y(a))a=new K(a,this);else if(a instanceof K)a.target=a.target||this;else{var d=a;a=new K(b,this);Wa(a,d)}var d=1,f,c=c[b],b=j in c,e;if(b){f=[];for(e=this;e;e=e.$)f.push(e);e=c[j];e.f=e.b;for(var g=f.length-1;!a.n&&0<=g&&e.f;g--)a.currentTarget=f[g],d&=mb(e,f[g],a.type,j,a)&&a.O!=n}if(n in c)if(e=c[n],e.f=e.b,b)for(g=0;!a.n&&g<f.length&&e.f;g++)a.currentTarget=f[g],d&=mb(e,f[g],a.type,n,a)&&a.O!=n;else for(f=this;!a.n&&f&&e.f;f=f.$)a.currentTarget=
f,d&=mb(e,f,a.type,n,a)&&a.O!=n;a=Boolean(d)}else a=j;return a};v.i=function(){pb.aa.i.call(this);var a=0;if(this!=k){var b=z(this);if(O[b])for(var b=O[b],c=b.length-1;0<=c;c--)kb(b[c].key),a++}else Sa(M,function(b,c){kb(c);a++});this.$=k};function qb(a){if("function"==typeof a.G)return a.G();if(y(a))return a.split("");if(da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ta(a)}function rb(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(da(a)||y(a))cb(a,b,c);else{var d;if("function"==typeof a.V)d=a.V();else if("function"!=typeof a.G)if(da(a)||y(a)){d=[];for(var f=a.length,e=0;e<f;e++)d.push(e)}else d=Ua(a);else d=h;for(var f=qb(a),e=f.length,g=0;g<e;g++)b.call(c,f[g],d&&d[g],a)}};function sb(a,b){this.v={};this.c=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof sb?(c=a.V(),d=a.G()):(c=Ua(a),d=Ta(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}v=sb.prototype;v.b=0;v.Da=0;v.G=function(){tb(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.v[this.c[b]]);return a};v.V=function(){tb(this);return this.c.concat()};
function tb(a){if(a.b!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];Object.prototype.hasOwnProperty.call(a.v,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.b!=a.c.length){for(var f={},c=b=0;b<a.c.length;)d=a.c[b],Object.prototype.hasOwnProperty.call(f,d)||(a.c[c++]=d,f[d]=1),b++;a.c.length=c}}v.set=function(a,b){Object.prototype.hasOwnProperty.call(this.v,a)||(this.b++,this.c.push(a),this.Da++);this.v[a]=b};function ub(){}ub.prototype.C=k;var vb;function wb(){}D(wb,ub);function xb(a){return(a=yb(a))?new ActiveXObject(a):new XMLHttpRequest}function zb(a){var b={};yb(a)&&(b[0]=j,b[1]=j);return b}
function yb(a){if(!a.ia&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.ia=d}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.ia}vb=new wb;function Ab(a){return Bb(a||arguments.callee.caller,[])}
function Bb(a,b){var c=[];if(0<=bb(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Cb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=Cb(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(Bb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Cb(a){if(Db[a])return Db[a];a=String(a);if(!Db[a]){var b=/function ([^\(]+)/.exec(a);Db[a]=b?b[1]:"[Anonymous]"}return Db[a]}var Db={};function R(a,b,c,d,f){this.reset(a,b,c,d,f)}R.prototype.Ba=0;R.prototype.fa=k;R.prototype.ea=k;var Eb=0;R.prototype.reset=function(a,b,c,d,f){this.Ba="number"==typeof f?f:Eb++;this.Ka=d||la();this.t=a;this.wa=b;this.Ha=c;delete this.fa;delete this.ea};R.prototype.sa=function(a){this.t=a};function S(a){this.xa=a}S.prototype.N=k;S.prototype.t=k;S.prototype.S=k;S.prototype.ha=k;function Fb(a,b){this.name=a;this.value=b}Fb.prototype.toString=function(){return this.name};var Gb=new Fb("SEVERE",1E3),Hb=new Fb("WARNING",900),Ib=new Fb("CONFIG",700),Jb=new Fb("FINE",500);v=S.prototype;v.getParent=function(){return this.N};v.ga=function(){this.S||(this.S={});return this.S};v.sa=function(a){this.t=a};
function Kb(a){if(a.t)return a.t;if(a.N)return Kb(a.N);ab("Root logger has no level set.");return k}v.log=function(a,b,c){if(a.value>=Kb(this).value){a=this.va(a,b,c);b="log:"+a.wa;w.console&&(w.console.timeStamp?w.console.timeStamp(b):w.console.markTimeline&&w.console.markTimeline(b));w.msWriteProfilerMark&&w.msWriteProfilerMark(b);for(b=this;b;){c=b;var d=a;if(c.ha)for(var f=0,e=h;e=c.ha[f];f++)e(d);b=b.getParent()}}};
v.va=function(a,b,c){var d=new R(a,String(b),this.xa);if(c){d.fa=c;var f;var e=arguments.callee.caller;try{var g;var l=ba("window.location.href");if(y(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:l,stack:"Not available"};else{var m,q,r=n;try{m=c.lineNumber||c.Ga||"Not available"}catch(p){m="Not available",r=j}try{q=c.fileName||c.filename||c.sourceURL||l}catch(s){q="Not available",r=j}g=r||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:m,
fileName:q,stack:c.stack||"Not available"}:c}f="Message: "+oa(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+oa(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+oa(Ab(e)+"-> ")}catch(A){f="Exception trying to expose exception! You win, we lose. "+A}d.ea=f}return d};function T(a,b){a.log(Jb,b,h)}var Lb={},Mb=k;
function Nb(a){Mb||(Mb=new S(""),Lb[""]=Mb,Mb.sa(Ib));var b;if(!(b=Lb[a])){b=new S(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Nb(a.substr(0,c));c.ga()[d]=b;b.N=c;Lb[a]=b}return b};function Ob(a){J.call(this);this.headers=new sb;this.q=a||k}D(Ob,pb);Ob.prototype.e=Nb("goog.net.XhrIo");var Pb=/^https?$/i,Qb=[];function Rb(a){a.F();eb(Qb,a)}v=Ob.prototype;v.h=n;v.a=k;v.Q=k;v.J="";v.la="";v.r=0;v.s="";v.U=n;v.H=n;v.Y=n;v.j=n;v.P=0;v.l=k;v.ra="";v.Ea=n;
v.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.J+"; newUri="+a);b=b?b.toUpperCase():"GET";this.J=a;this.s="";this.r=0;this.la=b;this.U=n;this.h=j;this.a=this.q?xb(this.q):xb(vb);this.Q=this.q?this.q.C||(this.q.C=zb(this.q)):vb.C||(vb.C=zb(vb));this.a.onreadystatechange=ja(this.pa,this);try{T(this.e,U(this,"Opening Xhr")),this.Y=j,this.a.open(b,a,j),this.Y=n}catch(f){T(this.e,U(this,"Error opening Xhr: "+f.message));Sb(this,f);return}a=
c||"";var e=new sb(this.headers);d&&rb(d,function(a,b){e.set(b,a)});d=w.FormData&&a instanceof w.FormData;if(b="POST"==b)b=!Object.prototype.hasOwnProperty.call(e.v,"Content-Type")&&!d;b&&e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");rb(e,function(a,b){this.a.setRequestHeader(b,a)},this);this.ra&&(this.a.responseType=this.ra);"withCredentials"in this.a&&(this.a.withCredentials=this.Ea);try{this.l&&(w.clearTimeout(this.l),this.l=k),0<this.P&&(T(this.e,U(this,"Will abort after "+
this.P+"ms if incomplete")),this.l=w.setTimeout(ja(this.Ca,this),this.P)),T(this.e,U(this,"Sending request")),this.H=j,this.a.send(a),this.H=n}catch(g){T(this.e,U(this,"Send error: "+g.message)),Sb(this,g)}};v.Ca=function(){"undefined"!=typeof aa&&this.a&&(this.s="Timed out after "+this.P+"ms, aborting",this.r=8,T(this.e,U(this,this.s)),this.dispatchEvent("timeout"),this.abort(8))};function Sb(a,b){a.h=n;a.a&&(a.j=j,a.a.abort(),a.j=n);a.s=b;a.r=5;Tb(a);Ub(a)}
function Tb(a){a.U||(a.U=j,a.dispatchEvent("complete"),a.dispatchEvent("error"))}v.abort=function(a){this.a&&this.h&&(T(this.e,U(this,"Aborting")),this.h=n,this.j=j,this.a.abort(),this.j=n,this.r=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Ub(this))};v.i=function(){this.a&&(this.h&&(this.h=n,this.j=j,this.a.abort(),this.j=n),Ub(this,j));Ob.aa.i.call(this)};v.pa=function(){!this.Y&&!this.H&&!this.j?this.ya():Vb(this)};v.ya=function(){Vb(this)};
function Vb(a){if(a.h&&"undefined"!=typeof aa)if(a.Q[1]&&4==Wb(a)&&2==Xb(a))T(a.e,U(a,"Local request error detected and ignored"));else if(a.H&&4==Wb(a))w.setTimeout(ja(a.pa,a),0);else if(a.dispatchEvent("readystatechange"),4==Wb(a)){T(a.e,U(a,"Request complete"));a.h=n;try{var b=Xb(a),c,d;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:d=j;break a;default:d=n}if(!(c=d)){var f;if(f=0===b){var e=String(a.J).match(ob)[1]||k;if(!e&&self.location)var g=self.location.protocol,
e=g.substr(0,g.length-1);f=!Pb.test(e?e.toLowerCase():"")}c=f}if(c)a.dispatchEvent("complete"),a.dispatchEvent("success");else{a.r=6;var l;try{l=2<Wb(a)?a.a.statusText:""}catch(m){T(a.e,"Can not get status: "+m.message),l=""}a.s=l+" ["+Xb(a)+"]";Tb(a)}}finally{Ub(a)}}}
function Ub(a,b){if(a.a){var c=a.a,d=a.Q[0]?ca:k;a.a=k;a.Q=k;a.l&&(w.clearTimeout(a.l),a.l=k);b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(f){a.e.log(Gb,"Problem encountered resetting onreadystatechange: "+f.message,h)}}}function Wb(a){return a.a?a.a.readyState:0}function Xb(a){try{return 2<Wb(a)?a.a.status:-1}catch(b){return a.e.log(Hb,"Can not get status: "+b.message,h),-1}}function U(a,b){return b+" ["+a.la+" "+a.J+" "+Xb(a)+"]"};var V;V=function(){return j};var Yb;function Zb(a,b){var c;c=a.className;c=y(c)&&c.match(/\S+/g)||[];for(var d=fb(arguments,1),f=c.length+d.length,e=c,g=0;g<d.length;g++)0<=bb(e,d[g])||e.push(d[g]);a.className=c.join(" ");return c.length==f};var $b=!F||F&&9<=Ma,ac=!G&&!F||F&&F&&9<=Ma||G&&I("1.9.1");F&&I("9");var bc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function cc(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!$b&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',oa(g.name),'"');if(g.type){e.push(' type="',oa(g.type),'"');var l={};Wa(l,g);delete l.type;g=l}e.push(">");e=e.join("")}e=f.createElement(e);if(g)if(y(g))e.className=g;else if("array"==x(g))Zb.apply(k,[e].concat(g));else{var m=e;Sa(g,function(a,b){"style"==b?m.style.cssText=a:"class"==b?m.className=a:"for"==b?m.htmlFor=a:b in bc?m.setAttribute(bc[b],a):0==b.lastIndexOf("aria-",
0)||0==b.lastIndexOf("data-",0)?m.setAttribute(b,a):m[b]=a})}if(2<d.length)for(var q=f,r=e,f=function(a){a&&r.appendChild(y(a)?q.createTextNode(a):a)},g=2;g<d.length;g++){var p=d[g];if(da(p)&&!(ea(p)&&0<p.nodeType)){var s;a:{if(p&&"number"==typeof p.length){if(ea(p)){s="function"==typeof p.item||"string"==typeof p.item;break a}if("function"==x(p)){s="function"==typeof p.item;break a}}s=n}l=cb;if(s)if(s=p.length,0<s){for(var A=Array(s),u=0;u<s;u++)A[u]=p[u];p=A}else p=[];l(p,f)}else f(p)}return e}
function dc(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(b))}}function W(a){this.T=a||w.document||document}W.prototype.createElement=function(a){return this.T.createElement(a)};W.prototype.createTextNode=function(a){return this.T.createTextNode(a)};
W.prototype.appendChild=function(a,b){a.appendChild(b)};W.prototype.ga=function(a){return ac&&a.children!=h?a.children:db(a.childNodes,function(a){return 1==a.nodeType})};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
function ec(a,b){var c=b||[];a&&c.push(a);return c}var fc=H&&"BackCompat"==document.compatMode,gc=document.firstChild.children?"children":"childNodes",X=n;
function hc(a){function b(){0<=q&&(t.id=c(q,u).replace(/\\/g,""),q=-1);if(0<=r){var a=r==u?k:c(r,u);0>">~+".indexOf(a)?t.d=a:t.M=a;r=-1}0<=m&&(t.g.push(c(m+1,u).replace(/\\/g,"")),m=-1)}function c(b,c){return na(a.slice(b,c))}a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=[],f=-1,e=-1,g=-1,l=-1,m=-1,q=-1,r=-1,p="",s="",A,u=0,Dc=a.length,t=k,B=k;p=s,s=a.charAt(u),u<Dc;u++)if("\\"!=p)if(t||(A=u,t={o:k,k:[],B:[],g:[],d:k,M:k,id:k,W:function(){return X?this.za:this.d}},r=u),0<=f)if("]"==s){B.R?
B.Z=c(g||f+1,u):B.R=c(f+1,u);if((f=B.Z)&&('"'==f.charAt(0)||"'"==f.charAt(0)))B.Z=f.slice(1,-1);t.B.push(B);B=k;f=g=-1}else"="==s&&(g=0<="|~^$*".indexOf(p)?p:"",B.type=g+s,B.R=c(f+1,u-g.length),g=u+1);else 0<=e?")"==s&&(0<=l&&(B.value=c(e+1,u)),l=e=-1):"#"==s?(b(),q=u+1):"."==s?(b(),m=u):":"==s?(b(),l=u):"["==s?(b(),f=u,B={}):"("==s?(0<=l&&(B={name:c(l+1,u),value:k},t.k.push(B)),e=u):" "==s&&p!=s&&(b(),0<=l&&t.k.push({name:c(l+1,u)}),t.ma=t.k.length||t.B.length||t.g.length,t.Ja=t.o=c(A,u),t.za=t.d=
t.M?k:t.d||"*",t.d&&(t.d=t.d.toUpperCase()),d.length&&d[d.length-1].M&&(t.ja=d.pop(),t.o=t.ja.o+" "+t.o),d.push(t),t=k);return d}function ic(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function jc(a){return 1==a.nodeType}function kc(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(X?a.getAttribute(b):a.getAttribute(b,2))||""}
var lc={"*=":function(a,b){return function(c){return 0<=kc(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==kc(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+kc(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+kc(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+kc(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return kc(c,a)==b}}},mc="undefined"==
typeof document.firstChild.nextElementSibling,nc=!mc?"nextElementSibling":"nextSibling",oc=!mc?"previousElementSibling":"previousSibling",pc=mc?jc:V;function qc(a){for(;a=a[oc];)if(pc(a))return n;return j}function rc(a){for(;a=a[nc];)if(pc(a))return n;return j}function sc(a){var b=a.parentNode,c=0,d=b[gc],f=a._i||-1,e=b._l||-1;if(!d)return-1;d=d.length;if(e==d&&0<=f&&0<=e)return f;b._l=d;f=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[nc])pc(b)&&(b._i=++c,a===b&&(f=c));return f}
function tc(a){return!(sc(a)%2)}function uc(a){return sc(a)%2}
var wc={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return qc},"last-child":function(){return rc},"only-child":function(){return function(a){return!qc(a)||!rc(a)?n:j}},empty:function(){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return n}return j}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=hc(b)[0],d={m:1};"*"!=c.d&&(d.d=1);c.g.length||(d.g=1);var f=vc(c,d);return function(a){return!f(a)}},"nth-child":function(a,b){if("odd"==b)return uc;if("even"==b)return tc;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,f=c[1]?parseInt(c[1],10):0,e=0,g=-1;0<d?0>f?f=f%d&&d+f%d:0<f&&(f>=d&&(e=f-f%d),f%=d):0>d&&(d*=-1,0<f&&(g=f,f%=d));if(0<d)return function(a){a=sc(a);return a>=e&&(0>g||a<=g)&&a%d==f};b=f}var l=parseInt(b,10);return function(a){return sc(a)==
l}}},xc=F?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return X?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function vc(a,b){if(!a)return V;b=b||{};var c=k;b.m||(c=ic(c,jc));b.d||"*"!=a.d&&(c=ic(c,function(b){return b&&b.tagName==a.W()}));b.g||cb(a.g,function(a,b){var e=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=ic(c,function(a){return e.test(a.className)});c.count=b});b.k||cb(a.k,function(a){var b=a.name;wc[b]&&(c=ic(c,wc[b](b,a.value)))});b.B||cb(a.B,function(a){var b,e=a.R;a.type&&lc[a.type]?b=lc[a.type](e,a.Z):e.length&&(b=xc(e));b&&(c=ic(c,b))});b.id||a.id&&(c=ic(c,function(b){return!!b&&b.id==a.id}));c||
"default"in b||(c=V);return c}var yc={};
function zc(a){var b=yc[a.o];if(b)return b;var c=a.ja,c=c?c.M:"",d=vc(a,{m:1}),f="*"==a.d,e=document.getElementsByClassName;if(c)if(e={m:1},f&&(e.d=1),d=vc(a,e),"+"==c)var g=d,b=function(a,b,c){for(;a=a[nc];)if(!mc||jc(a)){(!c||Ac(a,c))&&g(a)&&b.push(a);break}return b};else if("~"==c)var l=d,b=function(a,b,c){for(a=a[nc];a;){if(pc(a)){if(c&&!Ac(a,c))break;l(a)&&b.push(a)}a=a[nc]}return b};else{if(">"==c)var m=d,m=m||V,b=function(a,b,c){for(var d=0,e=a[gc];a=e[d++];)pc(a)&&((!c||Ac(a,c))&&m(a,d))&&
b.push(a);return b}}else if(a.id)d=!a.ma&&f?V:vc(a,{m:1,id:1}),b=function(b,c){var e;e=b?new W(9==b.nodeType?b:b.ownerDocument||b.document):Yb||(Yb=new W);var f=a.id;if(f=(e=y(f)?e.T.getElementById(f):f)&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return ec(e,c)};else if(e&&/\{\s*\[native code\]\s*\}/.test(String(e))&&a.g.length&&!fc)var d=vc(a,{m:1,g:1,id:1}),q=a.g.join(" "),b=function(a,b){for(var c=ec(0,b),e,f=0,g=a.getElementsByClassName(q);e=g[f++];)d(e,
a)&&c.push(e);return c};else!f&&!a.ma?b=function(b,c){for(var d=ec(0,c),e,f=0,g=b.getElementsByTagName(a.W());e=g[f++];)d.push(e);return d}:(d=vc(a,{m:1,d:1,id:1}),b=function(b,c){for(var e=ec(0,c),f,g=0,l=b.getElementsByTagName(a.W());f=l[g++];)d(f,b)&&e.push(f);return e});return yc[a.o]=b}var Bc={},Cc={};
function Ec(a){var b=hc(na(a));if(1==b.length){var c=zc(b[0]);return function(a){if(a=c(a,[]))a.L=j;return a}}return function(a){a=ec(a);for(var c,e,g=b.length,l,m,q=0;q<g;q++){m=[];c=b[q];e=a.length-1;0<e&&(l={},m.L=j);e=zc(c);for(var r=0;c=a[r];r++)e(c,m,l);if(!m.length)break;a=m}return m}}var Fc=!!document.querySelectorAll&&(!H||I("526"));
function Gc(a,b){if(Fc){var c=Cc[a];if(c&&!b)return c}if(c=Bc[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=j);if(Fc&&!b&&-1==">~+".indexOf(c)&&(!F||-1==a.indexOf(":"))&&!(fc&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var f=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return Cc[a]=function(b){try{if(!(9==b.nodeType||d))throw"";var c=b.querySelectorAll(f);F?c.ta=j:c.L=j;return c}catch(e){return Gc(a,j)(b)}}}var e=a.split(/\s*,\s*/);return Bc[a]=
2>e.length?Ec(a):function(a){for(var b=0,c=[],d;d=e[b++];)c=c.concat(Ec(d)(a));return c}}var Y=0,Hc=F?function(a){return X?a.getAttribute("_uid")||a.setAttribute("_uid",++Y)||Y:a.uniqueID}:function(a){return a._uid||(a._uid=++Y)};function Ac(a,b){if(!b)return 1;var c=Hc(a);return!b[c]?b[c]=1:0}
function Ic(a){if(a&&a.L)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;Y++;if(F&&X){var c=Y+"";a[0].setAttribute("_zipIdx",c);for(var d=1,f;f=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(f),f.setAttribute("_zipIdx",c)}else if(F&&a.ta)try{for(d=1;f=a[d];d++)jc(f)&&b.push(f)}catch(e){}else{a[0]&&(a[0]._zipIdx=Y);for(d=1;f=a[d];d++)a[d]._zipIdx!=Y&&b.push(f),f._zipIdx=Y}return b}
function Jc(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!y(a))return[a];if(y(b)&&(b=y(b)?document.getElementById(b):b,!b))return[];b=b||document;var c=b.ownerDocument||b.documentElement;X=b.contentType&&"application/xml"==b.contentType||Aa&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(F?c.xml:b.xmlVersion||c.xmlVersion);return(c=Gc(a)(b))&&c.L?c:Ic(c)}Jc.k=wc;C("goog.dom.query",Jc);C("goog.dom.query.pseudos",Jc.k);function Z(a,b,c){this.w=a;this.z=b;this.A=c}C("concerto.player.Settings",Z);Z.screen_id=Z.w;Z.server_url=Z.z;Z.server_version=Z.A;Z.prototype.save=function(){localStorage.screen_id=this.w;localStorage.server_url=this.z;localStorage.server_version=this.A};C("concerto.player.Settings.save",Z.prototype.save);Z.prototype.load=function(){this.w=localStorage.screen_id;this.z=localStorage.server_url;this.A=localStorage.server_version};C("concerto.player.Settings.load",Z.prototype.load);
Z.prototype.url=function(){return 1==this.A?this.z+"/screen/?mac="+this.w:2==this.A?this.z+"/frontend/"+this.w:k};C("concerto.player.Settings.url",Z.prototype.url);C("concerto.player.Settings",Z);function Kc(a){67==a.keyCode?window.location="settings.html":65!=a.keyCode&&76==a.keyCode&&(a=new Z,a.load(),window.location=a.url())}
function Lc(){if(navigator.onLine){var a=new Z;a.load();var b=a.url(),c=function(b){400>Xb(b.target)?window.location=a.url():(dc(y("status-message")?document.getElementById("status-message"):"status-message","Unable to contact Concerto server.  Please check configuration."),setInterval(function(){window.location.reload(j)},1E4))},d=new Ob;Qb.push(d);c&&Q(d,"complete",c);Q(d,"ready",ka(Rb,d));d.send(b,h,h,h)}else window.location.reload(j)}C("concerto.player.Settings.load",Z.load);
Q(window,"load",function(){var a=cc("div",{id:"status-message"},"Initializing...");(y("container")?document.getElementById("container"):"container").appendChild(a);Q(document,"keyup",Kc);var b=new Z;b.load();b.url()==k?window.location="settings.html":navigator.onLine?setInterval(Lc,5E3):(dc(a,"No internet connectivity."),setInterval(function(){window.location.reload(j)},1E4))});
