var k=void 0,l=!0,m=null,q=!1,u,w=this;
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function x(a){return"string"==typeof a}var y="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ba=0;function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function B(a,b,c){B=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return B.apply(m,arguments)}
function C(a,b){var c=a.split("."),d=w;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==k?d[e]=b:d=d[e]?d[e]:d[e]={}};function ea(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};var D,fa,ga,ha;function ia(){return w.navigator?w.navigator.userAgent:m}ha=ga=fa=D=q;var ja;if(ja=ia()){var ka=w.navigator;D=0==ja.indexOf("Opera");fa=!D&&-1!=ja.indexOf("MSIE");ga=!D&&-1!=ja.indexOf("WebKit");ha=!D&&!ga&&"Gecko"==ka.product}var la=D,E=fa,F=ha,G=ga,ma=w.navigator,na=-1!=(ma&&ma.platform||"").indexOf("Mac");function oa(){var a=w.document;return a?a.documentMode:k}var pa;
a:{var qa="",H;if(la&&w.opera)var ra=w.opera.version,qa="function"==typeof ra?ra():ra;else if(F?H=/rv\:([^\);]+)(\)|;)/:E?H=/MSIE\s+([^\);]+)(\)|;)/:G&&(H=/WebKit\/(\S+)/),H)var sa=H.exec(ia()),qa=sa?sa[1]:"";if(E){var ta=oa();if(ta>parseFloat(qa)){pa=String(ta);break a}}pa=qa}var ua={};
function I(a){var b;if(!(b=ua[a])){b=0;for(var c=ea(String(pa)).split("."),d=ea(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",j=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var r=j.exec(g)||["","",""],s=n.exec(h)||["","",""];if(0==r[0].length&&0==s[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==s[1].length?0:parseInt(s[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==s[1].length?0:parseInt(s[1],10))?1:0)||((0==r[2].length)<
(0==s[2].length)?-1:(0==r[2].length)>(0==s[2].length)?1:0)||(r[2]<s[2]?-1:r[2]>s[2]?1:0)}while(0==b)}b=ua[a]=0<=b}return b}var va=w.document,wa=!va||!E?k:oa()||("CSS1Compat"==va.compatMode?parseInt(pa,10):5);function J(a,b){this.type=a;this.currentTarget=this.target=b}J.prototype.A=q;J.prototype.defaultPrevented=q;J.prototype.R=l;J.prototype.preventDefault=function(){this.defaultPrevented=l;this.R=q};function xa(){}var ya=0;u=xa.prototype;u.key=0;u.l=q;u.n=q;u.p=function(a,b,c,d,e,f){if("function"==aa(a))this.H=l;else if(a&&a.handleEvent&&"function"==aa(a.handleEvent))this.H=q;else throw Error("Invalid listener argument");this.q=a;this.K=b;this.src=c;this.type=d;this.capture=!!e;this.F=f;this.n=q;this.key=++ya;this.l=q};u.handleEvent=function(a){return this.H?this.q.call(this.F||this.src,a):this.q.handleEvent.call(this.q,a)};var za=!E||E&&9<=wa,Aa=E&&!I("9");!G||I("528");F&&I("1.9b")||E&&I("8")||la&&I("9.5")||G&&I("528");F&&!I("8")||E&&I("9");var K=Array.prototype,Ba=K.indexOf?function(a,b,c){return K.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(x(a))return!x(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ca=K.forEach?function(a,b,c){K.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function Da(a,b,c){return 2>=arguments.length?K.slice.call(a,b):K.slice.call(a,b,c)};function Ea(a){Ea[" "](a);return a}Ea[" "]=function(){};function L(a,b){a&&this.p(a,b)}function Fa(){}Fa.prototype=J.prototype;L.S=J.prototype;L.prototype=new Fa;u=L.prototype;u.constructor=L;u.target=m;u.relatedTarget=m;u.offsetX=0;u.offsetY=0;u.clientX=0;u.clientY=0;u.screenX=0;u.screenY=0;u.button=0;u.keyCode=0;u.charCode=0;u.ctrlKey=q;u.altKey=q;u.shiftKey=q;u.metaKey=q;u.Q=q;u.D=m;
u.p=function(a,b){var c=this.type=a.type;J.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(F){var e;a:{try{Ea(d.nodeName);e=l;break a}catch(f){}e=q}e||(d=m)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=G||a.offsetX!==k?a.offsetX:a.layerX;this.offsetY=G||a.offsetY!==k?a.offsetY:a.layerY;this.clientX=a.clientX!==k?a.clientX:a.pageX;this.clientY=a.clientY!==k?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Q=na?a.metaKey:a.ctrlKey;this.state=a.state;this.D=a;a.defaultPrevented&&this.preventDefault();delete this.A};
u.preventDefault=function(){L.S.preventDefault.call(this);var a=this.D;if(a.preventDefault)a.preventDefault();else if(a.returnValue=q,Aa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var M={},N={},O={},P={};
function Ga(a,b,c,d,e){if("array"==aa(b))for(var f=0;f<b.length;f++)Ga(a,b[f],c,d,e);else a:{if(!b)throw Error("Invalid event type");d=!!d;var g=N;b in g||(g[b]={c:0,g:0});g=g[b];d in g||(g[d]={c:0,g:0},g.c++);var g=g[d],f=a[y]||(a[y]=++ba),h;g.g++;if(g[f]){h=g[f];for(var j=0;j<h.length;j++)if(g=h[j],g.q==c&&g.F==e){if(g.l)break;h[j].n=q;break a}}else h=g[f]=[],g.c++;var n=Ha,r=za?function(a){return n.call(r.src,r.key,a)}:function(a){a=n.call(r.src,r.key,a);if(!a)return a},j=r;j.src=a;g=new xa;g.p(c,
j,a,b,d,e);g.n=q;c=g.key;j.key=c;h.push(g);M[c]=g;O[f]||(O[f]=[]);O[f].push(g);a.addEventListener?(a==w||!a.M)&&a.addEventListener(b,j,d):a.attachEvent(b in P?P[b]:P[b]="on"+b,j)}}function Ia(a,b,c,d){if(!d.r&&d.J){for(var e=0,f=0;e<d.length;e++)d[e].l?d[e].K.src=m:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.J=q;0==f&&(delete N[a][b][c],N[a][b].c--,0==N[a][b].c&&(delete N[a][b],N[a].c--),0==N[a].c&&delete N[a])}}
function Ja(a,b,c,d,e){var f=1;b=b[y]||(b[y]=++ba);if(a[b]){a.g--;a=a[b];a.r?a.r++:a.r=1;try{for(var g=a.length,h=0;h<g;h++){var j=a[h];j&&!j.l&&(f&=Ka(j,e)!==q)}}finally{a.r--,Ia(c,d,b,a)}}return Boolean(f)}
function Ka(a,b){if(a.n){var c=a.key;if(M[c]){var d=M[c];if(!d.l){var e=d.src,f=d.type,g=d.K,h=d.capture;e.removeEventListener?(e==w||!e.M)&&e.removeEventListener(f,g,h):e.detachEvent&&e.detachEvent(f in P?P[f]:P[f]="on"+f,g);e=e[y]||(e[y]=++ba);if(O[e]){var g=O[e],j=Ba(g,d);0<=j&&K.splice.call(g,j,1);0==g.length&&delete O[e]}d.l=l;if(d=N[f][h][e])d.J=l,Ia(f,h,e,d);delete M[c]}}}return a.handleEvent(b)}
function Ha(a,b){if(!M[a])return l;var c=M[a],d=c.type,e=N;if(!(d in e))return l;var e=e[d],f,g;if(!za){var h;if(!(h=b))a:{h=["window","event"];for(var j=w;f=h.shift();)if(j[f]!=m)j=j[f];else{h=m;break a}h=j}f=h;h=l in e;j=q in e;if(h){if(0>f.keyCode||f.returnValue!=k)return l;a:{var n=q;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(r){n=l}if(n||f.returnValue==k)f.returnValue=l}}n=new L;n.p(f,this);f=l;try{if(h){for(var s=[],v=n.currentTarget;v;v=v.parentNode)s.push(v);g=e[l];g.g=g.c;for(var A=s.length-
1;!n.A&&0<=A&&g.g;A--)n.currentTarget=s[A],f&=Ja(g,s[A],d,l,n);if(j){g=e[q];g.g=g.c;for(A=0;!n.A&&A<s.length&&g.g;A++)n.currentTarget=s[A],f&=Ja(g,s[A],d,q,n)}}else f=Ka(c,n)}finally{s&&(s.length=0)}return f}d=new L(b,this);return f=Ka(c,d)};function Q(a,b,c){this.h=a;this.i=b;this.e=c}C("concerto.player.Settings",Q);Q.screen_id=Q.h;Q.server_url=Q.i;Q.server_version=Q.e;Q.prototype.save=function(){localStorage.screen_id=this.h;localStorage.server_url=this.i;localStorage.server_version=this.e};C("concerto.player.Settings.save",Q.prototype.save);Q.prototype.load=function(){this.h=localStorage.screen_id;this.i=localStorage.server_url;this.e=localStorage.server_version};C("concerto.player.Settings.load",Q.prototype.load);
Q.prototype.url=function(){return 1==this.e?this.i+"/screen/?mac="+this.h:2==this.e?this.i+"/frontend/"+this.h:m};C("concerto.player.Settings.url",Q.prototype.url);var R;R=function(){return l};var La;function Ma(a,b){var c;c=a.className;c=x(c)&&c.match(/\S+/g)||[];for(var d=Da(arguments,1),e=c,f=0;f<d.length;f++)0<=Ba(e,d[f])||e.push(d[f]);a.className=c.join(" ")};!F&&!E||E&&E&&9<=wa||F&&I("1.9.1");E&&I("9");function S(a){return x(a)?document.getElementById(a):a}function Na(a,b){function c(b,c){"style"==c?a.style.cssText=b:"class"==c?a.className=b:"for"==c?a.htmlFor=b:c in Oa?a.setAttribute(Oa[c],b):0==c.lastIndexOf("aria-",0)||0==c.lastIndexOf("data-",0)?a.setAttribute(c,b):a[c]=b}for(var d in b)c.call(k,b[d],d)}
var Oa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Pa(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(b))}}function Qa(a){this.B=a||w.document||document}Qa.prototype.createTextNode=function(a){return this.B.createTextNode(a)};Qa.prototype.appendChild=function(a,b){a.appendChild(b)};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
function T(a,b){var c=b||[];a&&c.push(a);return c}var Ra=G&&"BackCompat"==document.compatMode,Sa=document.firstChild.children?"children":"childNodes",U=q;
function Ta(a){function b(){0<=n&&(p.id=c(n,t).replace(/\\/g,""),n=-1);if(0<=r){var a=r==t?m:c(r,t);0>">~+".indexOf(a)?p.a=a:p.t=a;r=-1}0<=j&&(p.b.push(c(j+1,t).replace(/\\/g,"")),j=-1)}function c(b,c){return ea(a.slice(b,c))}a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=[],e=-1,f=-1,g=-1,h=-1,j=-1,n=-1,r=-1,s="",v="",A,t=0,nb=a.length,p=m,z=m;s=v,v=a.charAt(t),t<nb;t++)if("\\"!=s)if(p||(A=t,p={k:m,f:[],m:[],b:[],a:m,t:m,id:m,w:function(){return U?this.P:this.a}},r=t),0<=e)if("]"==v){z.u?
z.z=c(g||e+1,t):z.u=c(e+1,t);if((e=z.z)&&('"'==e.charAt(0)||"'"==e.charAt(0)))z.z=e.slice(1,-1);p.m.push(z);z=m;e=g=-1}else"="==v&&(g=0<="|~^$*".indexOf(s)?s:"",z.type=g+v,z.u=c(e+1,t-g.length),g=t+1);else 0<=f?")"==v&&(0<=h&&(z.value=c(f+1,t)),h=f=-1):"#"==v?(b(),n=t+1):"."==v?(b(),j=t):":"==v?(b(),h=t):"["==v?(b(),e=t,z={}):"("==v?(0<=h&&(z={name:c(h+1,t),value:m},p.f.push(z)),f=t):" "==v&&s!=v&&(b(),0<=h&&p.f.push({name:c(h+1,t)}),p.I=p.f.length||p.m.length||p.b.length,p.T=p.k=c(A,t),p.P=p.a=p.t?
m:p.a||"*",p.a&&(p.a=p.a.toUpperCase()),d.length&&d[d.length-1].t&&(p.G=d.pop(),p.k=p.G.k+" "+p.k),d.push(p),p=m);return d}function V(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function Ua(a){return 1==a.nodeType}function W(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(U?a.getAttribute(b):a.getAttribute(b,2))||""}
var Va={"*=":function(a,b){return function(c){return 0<=W(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==W(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+W(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+W(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+W(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return W(c,a)==b}}},Wa="undefined"==
typeof document.firstChild.nextElementSibling,X=!Wa?"nextElementSibling":"nextSibling",Xa=!Wa?"previousElementSibling":"previousSibling",Y=Wa?Ua:R;function Ya(a){for(;a=a[Xa];)if(Y(a))return q;return l}function Za(a){for(;a=a[X];)if(Y(a))return q;return l}function $a(a){var b=a.parentNode,c=0,d=b[Sa],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[X])Y(b)&&(b._i=++c,a===b&&(e=c));return e}
function ab(a){return!($a(a)%2)}function bb(a){return $a(a)%2}
var cb={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Ya},"last-child":function(){return Za},"only-child":function(){return function(a){return!Ya(a)||!Za(a)?q:l}},empty:function(){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return q}return l}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=Ta(b)[0],d={j:1};"*"!=c.a&&(d.a=1);c.b.length||(d.b=1);var e=Z(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return bb;if("even"==b)return ab;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(g=e,e%=d));if(0<d)return function(a){a=$a(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var h=parseInt(b,10);return function(a){return $a(a)==
h}}},db=E?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return U?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function Z(a,b){if(!a)return R;b=b||{};var c=m;b.j||(c=V(c,Ua));b.a||"*"!=a.a&&(c=V(c,function(b){return b&&b.tagName==a.w()}));b.b||Ca(a.b,function(a,b){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=V(c,function(a){return f.test(a.className)});c.count=b});b.f||Ca(a.f,function(a){var b=a.name;cb[b]&&(c=V(c,cb[b](b,a.value)))});b.m||Ca(a.m,function(a){var b,f=a.u;a.type&&Va[a.type]?b=Va[a.type](f,a.z):f.length&&(b=db(f));b&&(c=V(c,b))});b.id||a.id&&(c=V(c,function(b){return!!b&&b.id==a.id}));c||"default"in
b||(c=R);return c}var eb={};
function fb(a){var b=eb[a.k];if(b)return b;var c=a.G,c=c?c.t:"",d=Z(a,{j:1}),e="*"==a.a,f=document.getElementsByClassName;if(c)if(f={j:1},e&&(f.a=1),d=Z(a,f),"+"==c)var g=d,b=function(a,b,c){for(;a=a[X];)if(!Wa||Ua(a)){(!c||gb(a,c))&&g(a)&&b.push(a);break}return b};else if("~"==c)var h=d,b=function(a,b,c){for(a=a[X];a;){if(Y(a)){if(c&&!gb(a,c))break;h(a)&&b.push(a)}a=a[X]}return b};else{if(">"==c)var j=d,j=j||R,b=function(a,b,c){for(var d=0,e=a[Sa];a=e[d++];)Y(a)&&((!c||gb(a,c))&&j(a,d))&&b.push(a);
return b}}else if(a.id)d=!a.I&&e?R:Z(a,{j:1,id:1}),b=function(b,c){var e;e=b?new Qa(9==b.nodeType?b:b.ownerDocument||b.document):La||(La=new Qa);var f=a.id;if(f=(e=x(f)?e.B.getElementById(f):f)&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return T(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.b.length&&!Ra)var d=Z(a,{j:1,b:1,id:1}),n=a.b.join(" "),b=function(a,b){for(var c=T(0,b),e,f=0,g=a.getElementsByClassName(n);e=g[f++];)d(e,a)&&c.push(e);
return c};else!e&&!a.I?b=function(b,c){for(var d=T(0,c),e,f=0,g=b.getElementsByTagName(a.w());e=g[f++];)d.push(e);return d}:(d=Z(a,{j:1,a:1,id:1}),b=function(b,c){for(var e=T(0,c),f,g=0,h=b.getElementsByTagName(a.w());f=h[g++];)d(f,b)&&e.push(f);return e});return eb[a.k]=b}var hb={},ib={};
function jb(a){var b=Ta(ea(a));if(1==b.length){var c=fb(b[0]);return function(a){if(a=c(a,[]))a.s=l;return a}}return function(a){a=T(a);for(var c,f,g=b.length,h,j,n=0;n<g;n++){j=[];c=b[n];f=a.length-1;0<f&&(h={},j.s=l);f=fb(c);for(var r=0;c=a[r];r++)f(c,j,h);if(!j.length)break;a=j}return j}}var kb=!!document.querySelectorAll&&(!G||I("526"));
function lb(a,b){if(kb){var c=ib[a];if(c&&!b)return c}if(c=hb[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=l);if(kb&&!b&&-1==">~+".indexOf(c)&&(!E||-1==a.indexOf(":"))&&!(Ra&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var e=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return ib[a]=function(b){try{if(!(9==b.nodeType||d))throw"";var c=b.querySelectorAll(e);E?c.L=l:c.s=l;return c}catch(f){return lb(a,l)(b)}}}var f=a.split(/\s*,\s*/);return hb[a]=
2>f.length?jb(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat(jb(d)(a));return c}}var $=0,mb=E?function(a){return U?a.getAttribute("_uid")||a.setAttribute("_uid",++$)||$:a.uniqueID}:function(a){return a._uid||(a._uid=++$)};function gb(a,b){if(!b)return 1;var c=mb(a);return!b[c]?b[c]=1:0}
function ob(a){if(a&&a.s)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;$++;if(E&&U){var c=$+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(E&&a.L)try{for(d=1;e=a[d];d++)Ua(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=$);for(d=1;e=a[d];d++)a[d]._zipIdx!=$&&b.push(e),e._zipIdx=$}return b}
function pb(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!x(a))return[a];if(x(b)&&(b=S(b),!b))return[];b=b||document;var c=b.ownerDocument||b.documentElement;U=b.contentType&&"application/xml"==b.contentType||la&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(E?c.xml:b.xmlVersion||c.xmlVersion);return(c=lb(a)(b))&&c.s?c:ob(c)}pb.f=cb;C("goog.dom.query",pb);C("goog.dom.query.pseudos",pb.f);function qb(a){var b=a.type;if(b===k)return m;switch(b.toLowerCase()){case "checkbox":case "radio":return a.checked?a.value:m;case "select-one":return b=a.selectedIndex,0<=b?a.options[b].value:m;case "select-multiple":for(var b=[],c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:m;default:return a.value!==k?a.value:m}}
function rb(a,b){var c=a.type;if(c!==k)switch(c.toLowerCase()){case "checkbox":case "radio":a.checked=b?"checked":m;break;case "select-one":a.selectedIndex=-1;if(x(b))for(var d=0;c=a.options[d];d++)if(c.value==b){c.selected=l;break}break;case "select-multiple":c=b;x(c)&&(c=[c]);for(var e=0;d=a.options[e];e++)if(d.selected=q,c)for(var f,g=0;f=c[g];g++)d.value==f&&(d.selected=l);break;default:a.value=b!=m?b:""}};function sb(){this.d=new Q;this.d.load()}C("concerto.player.Settings",Q);
sb.prototype.load=function(){this.N=pb("label[for=mac]")[0];this.v=S("mac");this.C=S("endpoint");this.o=S("version");this.O=S("save");var a=B(function(){var a=this.N,b=this.v,c=qb(this.o);1==c?(Pa(a,"MAC Address"),Na(b,{placeholder:"0F:DE:AD:BE:EF"})):2==c&&(Pa(a,"Screen ID"),Na(b,{placeholder:"1"}))},this),b=this.d.h,c=this.d.i,d=this.d.e;this.d.e!=k&&Ma(S("flash"),"hidden");rb(this.v,b);rb(this.C,c);rb(this.o,d);a();Ga(this.o,"change",a);a=B(function(){this.d.h=qb(this.v);this.d.i=qb(this.C);this.d.e=
qb(this.o);this.d.save()},this);Ga(this.O,"click",a)};var tb=new sb;Ga(window,"load",B(tb.load,tb));
